# Generated by Django 3.0.5 on 2020-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant')], default='OWNER', max_length=50, verbose_name='Type'),
        ),
    ]
