# Generated by Django 3.0.5 on 2020-11-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_type'),
    ]

    operations = [
        migrations.RenameField('UserProfile', 'type', 'default_type'),
    ]
