# Generated by Django 3.0.5 on 2020-11-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201116_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('TENANT', 'Tenant')], default='OWNER', max_length=50, verbose_name='Types'),
        ),
    ]
