# Generated by Django 3.0.5 on 2020-11-24 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_check_in',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='book_check_out',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
