# Generated by Django 3.0.5 on 2020-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='monthly_price',
            new_name='daily_price',
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
